POST http://localhost:8888/api/v1/auth/jwt/login
accept: application/json
Content-Type: application/x-www-form-urlencoded

grant_type = password &
username = user &
password = test &
scope =  &
c
lient_id = s tring &
c
lient_secret = s tring

> {%
    client.global.set("access_token", response.body.access_token);
%}

###
POST http://localhost:8888/api/v1/task/create-task
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "header": "123",
  "description": "123"
}

###
#GET http://localhost:8989/api/v1/task/load_tasks
#Authorization: Bearer {{access_token}}
#accept: application/json

###

PATCH http://localhost:8888/api/v1/task/b927faa7-4571-4ad4-805f-e9245bfeec2a
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "status": "cancel"
}

