/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const email: typeof import('@vuelidate/validators')['email']
  const emailRule: typeof import('@/plugins/vuelidate/validation-rules')['emailRule']
  const getAuthToken: typeof import('@/utils/token')['getAuthToken']
  const getOrigin: typeof import('@/utils/api')['getOrigin']
  const handleResponse: typeof import('@/utils/api')['handleResponse']
  const helpers: typeof import('@vuelidate/validators')['helpers']
  const ipAdress: typeof import('@vuelidate/validators')['ipAdress']
  const ipRule: typeof import('@/plugins/vuelidate/validation-rules')['ipRule']
  const maxLength: typeof import('@vuelidate/validators')['maxLength']
  const maxLengthRule: typeof import('@/plugins/vuelidate/validation-rules')['maxLengthRule']
  const minLength: typeof import('@vuelidate/validators')['minLength']
  const minLengthRule: typeof import('@/plugins/vuelidate/validation-rules')['minLengthRule']
  const removeAuthToken: typeof import('@/utils/token')['removeAuthToken']
  const required: typeof import('@vuelidate/validators')['required']
  const requiredRule: typeof import('@/plugins/vuelidate/validation-rules')['requiredRule']
  const rtspRule: typeof import('@/plugins/vuelidate/validation-rules')['rtspRule']
  const setAuthToken: typeof import('@/utils/token')['setAuthToken']
  const usePasswordVisibility: typeof import('@/plugins/use-password-visibility')['usePasswordVisibility']
  const useVuelidate: typeof import('@vuelidate/core')['useVuelidate']
}
