"""Account table

Revision ID: 2c09d919ab18
Revises: 
Create Date: 2024-11-17 10:43:18.787298

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '2c09d919ab18'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role',
                    sa.Column('id', sa.Uuid(), nullable=False),
                    sa.Column('name', sa.String(length=50), nullable=False),
                    sa.Column('permissions', sa.JSON(), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('id')
                    )
    op.create_table('task',
                    sa.Column('id', sa.Uuid(), nullable=False),
                    sa.Column('header', sa.String(length=50), nullable=False),
                    sa.Column('description', sa.String(), nullable=False),
                    sa.Column('status', sa.String(), nullable=False),
                    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
                    sa.Column('user_id', sa.Uuid(), nullable=False),
                    sa.Column('executor_id', sa.Uuid(), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('id')
                    )
    op.create_table('user',
                    sa.Column('id', sa.Uuid(), nullable=False),
                    sa.Column('email', sa.String(length=50), nullable=False),
                    sa.Column('hashed_password', sa.String(length=1024), nullable=False),
                    sa.Column('is_active', sa.Boolean(), nullable=False),
                    sa.Column('is_superuser', sa.Boolean(), nullable=False),
                    sa.Column('is_verified', sa.Boolean(), nullable=False),
                    sa.Column('username', sa.String(length=30), nullable=True),
                    sa.Column('registered_at', sa.TIMESTAMP(), nullable=False),
                    sa.Column('role_id', sa.Uuid(), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('id')
                    )
    # ### end Alembic commands ###
    from datetime import datetime
    import uuid
    op.execute(
        f"""
        INSERT INTO role (id, name, permissions) VALUES
        ('adebb055-9b61-4f59-b1f2-824d007ca6a3', 'user', '{{"manage_users": true, "edit_content": true}}'),
        ('c72909a9-abd1-4903-9b0f-47a2c10e8681', 'base', '{{"manage_users": false, "edit_content": true}}'),
        ('2777c3c1-d0de-4a08-b13b-03743ec2fbe3', 'tech', '{{"manage_users": false, "edit_content": false}}')
        """
    )

    # Добавляем пользователей
    now = datetime.utcnow()
    op.execute("""
        INSERT INTO "user" (id, email, hashed_password, is_active, is_superuser, is_verified, username, registered_at, role_id) VALUES
        ('{}', 'user', '$argon2id$v=19$m=65536,t=3,p=4$/GtBDkDqjok8OaZgAxokLQ$DeMfnd3lHFFcQwJxqEnm3bud8ZlMde92hbxlhIXTPwo', true, true, true, 'admin', '{}', 'adebb055-9b61-4f59-b1f2-824d007ca6a3'),
        ('{}', 'editor', '$argon2id$v=19$m=65536,t=3,p=4$/GtBDkDqjok8OaZgAxokLQ$DeMfnd3lHFFcQwJxqEnm3bud8ZlMde92hbxlhIXTPwo', true, false, true, 'editor', '{}', 'c72909a9-abd1-4903-9b0f-47a2c10e8681'),
        ('{}', 'tech', '$argon2id$v=19$m=65536,t=3,p=4$/GtBDkDqjok8OaZgAxokLQ$DeMfnd3lHFFcQwJxqEnm3bud8ZlMde92hbxlhIXTPwo', true, false, true, 'viewer', '{}', '2777c3c1-d0de-4a08-b13b-03743ec2fbe3')
    """.format(uuid.uuid4(), now, uuid.uuid4(), now, uuid.uuid4(), now))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('task')
    op.drop_table('role')
    # ### end Alembic commands ###
